version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    govet:
      enable-all: true
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 140
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - hugeParam  # 88 bytes for Settings struct is acceptable for a builder pattern API

  exclusions:
    rules:
      # Exclude some linters from running on test files
      - path: '_test\.go'
        linters:
          - gocyclo
          - dupl
          - gosec
          - lll
          - errcheck     # Test code often intentionally ignores errors
          - goconst      # Test literals don't need to be constants
          - unparam      # Test helpers may have unused params for consistency

run:
  timeout: 5m
  tests: true
